website_url = "https://duckhunt.me/"

[bot]
prefixes = ["duckhunt", "dh!", "dh", "Dh", "Dh!", "dH!", "dH", "DH!", "DH"]
description = """Discord Version 4 of DuckHunt, the popular game bot"""
playing = "Ducks are everywhere"
commands_are_case_insensitive = true

[database]
# A postgreSQL database to store information about users, channels, and guilds
# Please ensure the database exist before loading the database modules
# Quick Start : https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e
enable = true
host = ""
port = ""
user = ""
password = ""
database = ""

[duckhunt_public_log]
server_id = 195260081036591104
channel_id = 793563942416416788

[auth.discord]
# Your bot token. You can find it on the Bot page of the Developper portal
token = ""

[cogs]
# Names of cogs to load. Usually cogs.file_name_without_py
# bots_list_and_voting must be loaded before rest_api
cogs_to_load = ['cogs.error_handling',
                'cogs.tags',
                'cogs.simple_commands',
                'cogs.background_loop',
                'cogs.support_server_commands',
                'cogs.settings_commands',
                'cogs.ducks_spawning_commands',
                'cogs.ducks_spawning',
                'cogs.ducks_hunting_commands',
                'cogs.statistics_experience_commands',
                'cogs.community',
                'cogs.private_messages_support',
                'cogs.random_ducks',
                'cogs.inventory_commands',
                'cogs.shopping_commands',
                'cogs.duck_boss',
                'cogs.prestige_commands',
                'cogs.bots_list_and_voting',
                'cogs.event2021',
                'cogs.rest_api',
                'jishaku',
                ]
# The name after cogs is the name of the class
[cogs.SimpleCommands]
wiki_url = "https://duckhunt.me/docs/"

[cogs.DuckBoss]
boss_channel_id = 794950988845940768
required_bangs = 40
role_ping_id = 803708518716014652


[cogs.SupportServerCommands]
# That's the ID of your server where the command will be ran
support_server_id = 195260081036591104
# ID of an empty channel that will be used as a status dashboard.
status_channel_id = 795389911163338775

[cogs.Community]
servers = [195260081036591104]
rpg_role_name = "Ping me for RPG bot events"
moderators_that_can_delete_with_reactions = [251996890369884161]

[cogs.PrivateMessagesSupport]
forwarding_category = 821732328018935818

[cogs.RestAPI]
listen_ip = "0.0.0.0"
listen_port = "8080"
route_prefix = "/api"
# Access keys are actually GUIDs/UUIDs.
# You can generate them easily. https://www.uuidgenerator.net/version4
global_access_keys = []

[cogs.Tags]
allowed_in_guilds = [
    195260081036591104, # DuckHunt Support Server
    734810932529856652, # DuckHunt Beta
    819743660895371315, # 765471470347485204's server because they asked nicely
]

[cogs.BotsListVoting]
statcord_token = "abcdef"

[cogs.Event2021]
# That's the ID of the server where the event will be enabled
server_id = 195260081036591104
scoreboard_channel_id = 852285234438471720
commands_channel_id = 852285369553780756
enabled_on = [
    852285369553780756,
    195260081036591104,
    441204489882435595,
    698797845334982676,
    750786468422615140,
    801874563117219870,
    195260818215010304,
    430396851024429081,
    799599320612864010,
]


[random_ducks]
assets_path = 'assets/Random Ducks'
composite_order = ['Body', 'Neck', 'Face', 'Hats'] # Background is included
